#!/bin/sh
# From-source bootstrap for the MesCC armv7l tcc reproducer.
#
# Builds, entirely from source, the toolchain needed to compile janneke's
# mes fork of tcc (tcc-0.9.26-1147-gee75a10c, the tarball live-bootstrap
# pins) for 32-bit ARM with MesCC:
#
#   1. oriansj/stage0-posix x86 tools from the hex0 seed (kaem, M2-Planet,
#      M1, hex2, blood-elf). The host arch is irrelevant: M2-Planet
#      cross-emits armv7l and M1/hex2 are architecture-parameterised byte
#      tools, so native x86-64 binaries produce armv7l output.
#   2. GNU Mes 0.27.1 (ftp.gnu.org) built into an armv7l `mes-m2` via mes's
#      own kaem.arm (M2-Planet --architecture armv7l), with the two known
#      mes-side arm fixes applied (see below).
#   3. nyacc 1.00.2 (MesCC's C parser).
#   4. the tcc source tarball, fetched and sha256-verified.
#
# Nothing is vendored except the tiny fix/support files in this repo. The
# per-mode assertions live in repro.sh; the mes arm libc archives (a slow
# MesCC compile) are built there, on demand, only for the modes that link.
set -eu

MES_VER=0.27.1
MES_SHA=183a40ea47ea49f8a1e3bd1b9d12e676374d64d63bc79e7bc1ae7d673dfdf25d
NYACC_URL=https://github.com/Googulator/nyacc/releases/download/V1.00.2-lb1/nyacc-1.00.2-lb1.tar.gz
NYACC_SHA=708c943f89c972910e9544ee077771acbd0a2c0fc6d33496fe158264ddb65327
TCC_PKG=tcc-0.9.26-1147-gee75a10c
TCC_URL=https://lilypond.org/janneke/tcc/$TCC_PKG.tar.gz
TCC_SHA=6b8cbd0a5fed0636d4f0f763a603247bc1935e206e1cc5bda6a2818bab6e819f

HERE=$(cd "$(dirname "$0")" && pwd)
WORK="$HERE/work"
rm -rf "$WORK"; mkdir -p "$WORK"; cd "$WORK"

echo "=== 1. stage0-posix: x86 tools from the hex0 seed ==="
git clone --depth 1 --recurse-submodules -q https://github.com/oriansj/stage0-posix
cd stage0-posix
rm -rf x86/artifact x86/bin; mkdir -p x86/artifact x86/bin
./bootstrap-seeds/POSIX/x86/kaem-optional-seed x86/mescc-tools-seed-kaem.kaem
./x86/artifact/kaem-0 x86/mescc-tools-mini-kaem.kaem
./x86/bin/kaem --verbose --strict --file x86/kaem.run
S0BIN="$WORK/stage0-posix/x86/bin"
for t in kaem M2-Planet M1 hex2 blood-elf; do
  test -x "$S0BIN/$t" || { echo "stage0 tool missing: $t"; exit 1; }
done
cd "$WORK"

echo "=== 2. GNU Mes $MES_VER + nyacc 1.00.2 source ==="
curl -fsSL -o "mes-$MES_VER.tar.gz" "https://ftp.gnu.org/gnu/mes/mes-$MES_VER.tar.gz"
echo "$MES_SHA  mes-$MES_VER.tar.gz" | sha256sum -c -
tar xzf "mes-$MES_VER.tar.gz"
curl -fsSL -o nyacc.tar.gz "$NYACC_URL"
echo "$NYACC_SHA  nyacc.tar.gz" | sha256sum -c -
tar xzf nyacc.tar.gz
NY="$WORK/nyacc-1.00.2/module"
test -d "$NY" || { echo "nyacc module dir missing"; exit 1; }

echo "=== 3. build armv7l mes-m2 (two mes-side arm fixes) ==="
M="$WORK/mes-$MES_VER"
cd "$M"
# minimal config.h: the M2 bootstrap path consumes only these two lines (the
# full one is generated by ./configure, which needs Guile).
printf '#undef SYSTEM_LIBC\n#define MES_VERSION "%s"\n' "$MES_VER" > include/mes/config.h
# fix A (upstream: bug-mes): mes 0.27.1's lib/m2/arm/arm_defs.M1 predates
# current M2-Planet armv7l codegen (no {R8}/{R9}/{R10}); without these
# kaem.arm dies at M1 "Received invalid other; {R8}".
cat "$HERE/arm_defs-additions.M1" >> lib/m2/arm/arm_defs.M1
# fix B (upstream: bug-mes): swap the stub __raise for a real one so that an
# uncaught MesCC error aborts with SIGABRT + a readable message instead of a
# SIGSEGV from abort()'s null-deref fallback. This is what makes bug 1's
# "parse failed ... on input {" diagnostic visible below.
cp "$HERE/mes-real-raise.c" lib/linux/raise.c
sed -i 's|-f ${srcdest}lib/stub/__raise.c|-f ${srcdest}lib/linux/raise.c|' kaem.run
# kaem.arm sets stage0_cpu=armv7l and invokes the default kaem.run.
PATH="$S0BIN:$PATH" "$S0BIN/kaem" --verbose --strict --file kaem.arm
test -x bin/mes-m2

echo "=== 4. generate mescc.scm (arm/linux) + include/arch shims ==="
sed -e "s|@prefix@|$M|g" -e "s|@VERSION@|$MES_VER|g" -e "s|@mes_cpu@|arm|g" \
    -e "s|@mes_kernel@|linux|g" -e "s|@guile_site_dir@||g" \
    -e "s|@guile_site_ccache_dir@||g" scripts/mescc.scm.in > mescc.scm
# arm-mes-mescc/syscall-internal.c includes <arch/syscall.h> etc.
mkdir -p include/arch
cp include/linux/arm/kernel-stat.h include/arch/kernel-stat.h
cp include/linux/arm/signal.h      include/arch/signal.h
cp include/linux/arm/syscall.h     include/arch/syscall.h

echo "=== 5. armv7l mes-m2 runs Scheme under qemu-arm ==="
QEMU=qemu-arm; command -v qemu-arm >/dev/null 2>&1 || QEMU=qemu-arm-static
GUILE_LOAD_PATH="$M/mes/module:$M/module" MES_PREFIX="$M" \
  "$QEMU" bin/mes-m2 -c "(display 'mes-m2-armv7l-ok)(newline)" | grep -q armv7l-ok

echo "=== 6. fetch + verify tcc source ($TCC_PKG) ==="
cd "$WORK"
curl -fsSL -o "$TCC_PKG.tar.gz" "$TCC_URL"
echo "$TCC_SHA  $TCC_PKG.tar.gz" | sha256sum -c -

cat > "$WORK/env" <<EOF
S0BIN=$S0BIN
M=$M
NY=$NY
WORK=$WORK
TCC_PKG=$TCC_PKG
QEMU=$QEMU
EOF
echo "=== bootstrap complete ==="
cat "$WORK/env"
